// Real estate agencies data
export const agencies = [
  {
    id: 1,
    name: "Realar Living Solutions",
    location: "California, USA",
    properties: 45,
    agents: 12,
    founded: 2015,
    image: "/real-estate-agency-office.jpg",
    description: "Premium real estate agency with over 20 years of combined experience",
    phone: "+01 234 567 890",
    email: "info@realar.com",
    rating: 4.8,
    reviews: 234,
  },
  {
    id: 2,
    name: "Solusi Property Group",
    location: "Toronto, Canada",
    properties: 38,
    agents: 10,
    founded: 2012,
    image: "/property-agency-office.jpg",
    description: "Dedicated to finding your dream property",
    phone: "+01 456 789 012",
    email: "contact@solusi.com",
    rating: 4.7,
    reviews: 189,
  },
  {
    id: 3,
    name: "Global Realty Services",
    location: "London, UK",
    properties: 52,
    agents: 15,
    founded: 2010,
    image: "/modern-real-estate-agency.jpg",
    description: "International property specialists",
    phone: "+44 123 456 7890",
    email: "hello@global-realty.com",
    rating: 4.9,
    reviews: 301,
  },
]
