// Property listings data
export const properties = [
  {
    id: 1,
    title: "Alpine House",
    location: "California, USA",
    price: 350000,
    beds: 4,
    baths: 3,
    area: 3200,
    image: "/modern-alpine-house-with-pool.jpg",
    rating: 4.8,
    reviews: 128,
    type: "House",
    description: "Spacious alpine-style home with pool and modern amenities",
    featured: true,
  },
  {
    id: 2,
    title: "Apartments Auckland",
    location: "Auckland, New Zealand",
    price: 250000,
    beds: 3,
    baths: 2,
    area: 2100,
    image: "/contemporary-apartment-building.jpg",
    rating: 4.6,
    reviews: 95,
    type: "Apartment",
    description: "Modern apartment with city views and premium finishes",
    featured: true,
  },
  {
    id: 3,
    title: "Holliday Luxury House",
    location: "Miami, USA",
    price: 450000,
    beds: 5,
    baths: 4,
    area: 4500,
    image: "/luxury-villa-pool.png",
    rating: 4.9,
    reviews: 156,
    type: "Villa",
    description: "Luxury holiday home with beachfront access",
    featured: true,
  },
  {
    id: 4,
    title: "Townside Residence",
    location: "Toronto, Canada",
    price: 320000,
    beds: 3,
    baths: 2.5,
    area: 2800,
    image: "/modern-townhouse.png",
    rating: 4.7,
    reviews: 112,
    type: "Townhouse",
    description: "Contemporary townhouse in prime location",
    featured: false,
  },
  {
    id: 5,
    title: "Contemporary Modern House",
    location: "Vancouver, Canada",
    price: 400000,
    beds: 4,
    baths: 3,
    area: 3600,
    image: "/contemporary-modern-house.jpg",
    rating: 4.8,
    reviews: 134,
    type: "House",
    description: "Contemporary architecture with energy-efficient systems",
    featured: false,
  },
  {
    id: 6,
    title: "Luxury Modern Home",
    location: "Sydney, Australia",
    price: 480000,
    beds: 5,
    baths: 4,
    area: 4200,
    image: "/luxury-modern-home-with-view.jpg",
    rating: 4.9,
    reviews: 178,
    type: "Luxury Home",
    description: "Stunning luxury residence with panoramic views",
    featured: false,
  },
]

export const propertyCategories = [
  { name: "All", count: 24 },
  { name: "House", count: 12 },
  { name: "Apartment", count: 8 },
  { name: "Villa", count: 3 },
  { name: "Townhouse", count: 1 },
]
